# To validate:
#   cat codecov.yml | curl --data-binary @- https://codecov.io/validate

codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 0%
        informational: true
    patch:
      default:
        enabled: no
        if_not_found: success

comment:
  layout: "reach, diff, files, flags"
  behavior: default
  require_changes: no
