name: flutterfire_gen_ts_annotation
description: flutterfire_gen_ts_annotation
version: 0.0.1-dev.1
homepage: https://github.com/KosukeSaigusa/flutterfire_gen

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.24.4
