name: flutterfire_gen_annotation
description: flutterfire_gen_annotation
version: 0.0.2-dev.1
homepage: https://github.com/KosukeSaigusa/flutterfire_gen

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.1

dev_dependencies:
  test: ^1.24.4
