name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutterfire_gen_annotation:
    path: ../../flutterfire_gen_annotation

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  flutterfire_gen:
    path: ../
