# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      flutterfire_gen:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/helper/*
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"

builders:
  flutterfire_gen:
    import: "package:flutterfire_gen/builder.dart"
    builder_factories: ["flutterfireGenBuilder"]
    build_extensions: {".dart": [".flutterfire_gen.dart"]}
    auto_apply: dependents
    build_to: source
    defaults:
      options:
        includePathField: true
        includeDocumentReferenceField: true
        generateCopyWith: true
