name: flutterfire_gen
description: flutterfire_gen
version: 0.0.1
homepage: https://github.com/KosukeSaigusa/flutterfire_gen

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  analyzer: ^6.0.0
  build: ^2.4.1
  cloud_firestore: ^4.8.2
  flutter:
    sdk: flutter
  flutterfire_gen_annotation: ^0.0.1-dev.1
  json_annotation: ^4.8.1
  meta: ^1.9.1
  source_gen: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.6
  fake_cloud_firestore: ^2.4.1+1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
