name: flutterfire_gen
description: flutterfire_gen
version: 0.0.1
homepage: https://github.com/KosukeSaigusa/flutterfire_gen

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  analyzer: ^5.13.0
  build: ^2.4.0
  cloud_firestore: ^4.8.1
  flutter:
    sdk: flutter
  flutterfire_gen_annotation:
    path: ../flutterfire_gen_annotation
  meta: ^1.9.1
  source_gen: ^1.3.2

dev_dependencies:
  build_runner: ^2.4.5
  fake_cloud_firestore: ^2.4.1+1
  flutter_test:
    sdk: flutter
