name: flutterfire_gen
description: flutterfire_gen
version: 0.0.1
homepage: https://github.com/KosukeSaigusa/flutterfire_gen

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  analyzer: ^6.0.0
  build: ^2.4.1
  cloud_firestore: ^4.8.2
  flutter:
    sdk: flutter
  flutterfire_gen_annotation:
    git:
      url: https://github.com/KosukeSaigusa/flutterfire_gen.git
      path: packages/flutterfire_gen_annotation
      ref: d85f2cf41aabe1dde0c4c17a9f6e852579ac2b6c
  json_annotation: ^4.8.1
  meta: ^1.9.1
  source_gen: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
