name: flutterfire_gen
description: flutterfire_gen
version: 0.2.0-dev.3
homepage: https://github.com/kosukesaigusa/flutterfire_gen

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  analyzer: ^6.1.0
  build: ^2.4.1
  cloud_firestore: ^4.11.0
  flutter:
    sdk: flutter
  flutterfire_gen_annotation: ^0.2.0-dev.1
  flutterfire_gen_utils: ^0.2.0-dev.1
  json_annotation: ^4.8.1
  meta: ^1.9.1
  path: ^1.8.3
  source_gen: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mockito: ^5.4.3
