name: flutterfire_gen_utils
description: flutterfire_gen_utils
version: 0.2.0-dev.1
homepage: https://github.com/kosukesaigusa/flutterfire_gen

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  cloud_firestore: ^4.8.2
  flutter:
    sdk: flutter
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
