name: flutterfire_gen_utils
description: flutterfire_gen_utils
version: 0.4.0
homepage: https://github.com/kosukesaigusa/flutterfire_gen

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  flutter:
    sdk: flutter
  meta: ^1.9.1

dev_dependencies:
  test: ^1.21.0
